### ISSUE TITLE
MKR1000 - Upload error. Error while erasing flash memory.

### ISSUE THREAD

**Issue by KevanE** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#40] opened 2019-04-17 01:04 UTC
Unable to resolve this error during Firmware Update. 
Upload error. Error while erasing flash memory.

Tried the following...
I've Reset the CPU with a 'double' reset button click.
I've updated the SAMD library to 1.6.21
I've never been able to update the WiFi101 firmware to 19.6.1

My MKR1000 has a Shield with the code: MR510PB Rev.R3

I could really use some help resolving this.

Thanks in advance.

Kevan Evans

**Comment by per1234** [comment] 2019-05-12 13:53
Closing as duplicate of https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/issues/41

**Closed as completed by per1234** 2019-05-12 13:53 UTC
Labels: conclusion: duplicate
